title: Trader Joe's Insights
description: Algorithmic Market Analysis & Risk Management
theme: jekyll-theme-cayman
url: "https://alexmorganbot.github.io"
baseurl: "/public_blog"
plugins:
  - jekyll-seo-tag
google_analytics: 
show_downloads: false
